name: Build Kivy App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython

    - name: Build Kivy app
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential ccache git libncurses5:i386 libstdc++6:i386 zlib1g:i386 libncurses5 libffi-dev libssl-dev
        sudo apt-get install -y liblzma-dev python3-pip libffi-dev libssl-dev
        sudo apt-get install -y openjdk-8-jdk
        sudo apt-get install -y unzip
        sudo apt-get install -y libffi6
        sudo apt-get install -y autoconf
        sudo apt-get install -y automake
        sudo apt-get install -y python-dev-is-python3
        sudo apt-get install -y python3-venv
        sudo apt-get install -y wget
        sudo apt-get install -y libjpeg-dev
        sudo apt-get install -y zlib1g-dev
        sudo apt-get install -y libpng-dev
        sudo apt-get install -y libtiff-dev
        sudo apt-get install -y libsm6
        sudo apt-get install -y libxext6
        sudo apt-get install -y libxrender1
        sudo apt-get install -y git-core
        pip install --upgrade pip
        pip install buildozer
        pip install cython==0.29.19
        buildozer android debug
      working-directory: .
